// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"code.cestus.io/libs/gotools/pkg/httpwares/requestid"
	"sync"
)

// Ensure, that SupplierMock does implement requestid.Supplier.
// If this is not the case, regenerate this file with moq.
var _ requestid.Supplier = &SupplierMock{}

// SupplierMock is a mock implementation of requestid.Supplier.
//
//	func TestSomethingThatUsesSupplier(t *testing.T) {
//
//		// make and configure a mocked requestid.Supplier
//		mockedSupplier := &SupplierMock{
//			GetFunc: func(key string) string {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(key string, value string)  {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedSupplier in code that requires requestid.Supplier
//		// and then make assertions.
//
//	}
type SupplierMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(key string) string

	// SetFunc mocks the Set method.
	SetFunc func(key string, value string)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
	}
	lockGet sync.RWMutex
	lockSet sync.RWMutex
}

// Get calls GetFunc.
func (mock *SupplierMock) Get(key string) string {
	if mock.GetFunc == nil {
		panic("SupplierMock.GetFunc: method is nil but Supplier.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSupplier.GetCalls())
func (mock *SupplierMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *SupplierMock) Set(key string, value string) {
	if mock.SetFunc == nil {
		panic("SupplierMock.SetFunc: method is nil but Supplier.Set was just called")
	}
	callInfo := struct {
		Key   string
		Value string
	}{
		Key:   key,
		Value: value,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	mock.SetFunc(key, value)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedSupplier.SetCalls())
func (mock *SupplierMock) SetCalls() []struct {
	Key   string
	Value string
} {
	var calls []struct {
		Key   string
		Value string
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
