.PHONY: generate
## Install tools
all:
#region CODE_REGION(project)
	go install github.com/onsi/ginkgo/v2/ginkgo@v2.23.3
	go install github.com/matryer/moq@v0.5.3
	go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.4
	go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
	go install github.com/abice/go-enum@v0.6.1
#endregion
#region CODE_REGION(service)
#endregion